version = 1
[custom]
enable_rule_generator = true
overwrite_original_rules = false
clash_rule_base = "https://cdn.jsdelivr.net/gh/veinkr/rules@main/base_scrap_config.yml"

[[custom_groups]]
name = "AUTO"
type = "url-test"
rule = ["[]LoadBalance", ".*"]
url = "http://www.gstatic.com/generate_204"
interval = 300

[[custom_groups]]
name = "DIRECTS"
type = "select"
rule = ["[]DIRECT"]

[[custom_groups]]
name = "Telegram"
type = "select"
rule = ["[]LoadBalance", ".*"]

[[custom_groups]]
name = "LoadBalance"
type = "load-balance"
rule = [
    "香港|新加坡|台湾|日本|美国|德国|法国|巴西"
]
strategy = "round-robin"
url = "https://telegra.ph"
interval = 1200
lazy = false

[[rulesets]]
group = "Telegram"
ruleset = "https://cdn.jsdelivr.net/gh/veinkr/rules@main/t.list"
type = "surge-ruleset"

[[rulesets]]
group = "DIRECTS"
ruleset = "[]GEOIP,CN"

[[rulesets]]
group = "AUTO"
ruleset = "[]FINAL"
